# Generated by Django 3.2.5 on 2021-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Task',
        ),
        migrations.AddField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Phase',
            field=models.CharField(choices=[('To do', 'to do'), ('In Progress', 'in progress'), ('Review', 'review'), ('Done', 'done')], default='To do', max_length=20),
        ),
    ]
