# Generated by Django 3.2.5 on 2021-08-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Index',
            field=models.IntegerField(default=1),
        ),
    ]
