# Generated by Django 3.2.5 on 2021-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210715_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='Tag',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
