# Generated by Django 3.2.5 on 2021-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210715_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Discription',
            field=models.TextField(max_length=400),
        ),
    ]
